name: chitfunds
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  intl: 
  path: ^1.9.0
   # Specify a version
  screenshot: 
 

  image:   # Specify a version

  permission_handler: 
 
  
  
  get: ^4.6.6
  esc_pos_printer: ^4.1.0
  flutter_blue_plus: ^1.34.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  dio: ^5.7.0
  pdf: ^3.8.4
  pdf_image_renderer: ^1.0.1
  flutter_downloader: ^1.11.8
  esc_pos_utils: ^1.1.0
  flutter_screenutil: ^5.9.3
  excel: ^4.0.6
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
 
